### ISSUE TITLE
live.js crashes after a few minutes

### ISSUE THREAD

**Issue by mikelmaron** [osmlab/osm-meta-util#5]
Running live.js, after a few minutes, get this error consistently

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:146:15)
    at MetaUtil.Readable.push (_stream_readable.js:127:10)
    at parserEnd (/home/mikel/Projects/osm-meta-util/index.js:57:18)
    at EventEmitter.emit (events.js:95:17)
    at Parser.parse (/home/mikel/Projects/osm-meta-util/node_modules/node-expat/lib/node-expat.js:23:22)
    at Parser.write (/home/mikel/Projects/osm-meta-util/node_modules/node-expat/lib/node-expat.js:60:16)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7)
    at Unzip.pipeOnReadable (_stream_readable.js:624:5)
    at Unzip.EventEmitter.emit (events.js:92:17)

**Comment by mikelmaron** [comment]
any suggestions to help debug this?

**Comment by kamicut** [comment]
I'm not really sure yet but I suspect that it has something to do with the rate of download? What parameters are you giving the MetaUtil function?

**Comment by mikelmaron** [comment]
I am simply running the live.js example  


     On Thursday, March 19, 2015 4:40 PM, Marc Farra <notifications@github.com> wrote:
   
 

 I'm not really sure yet but I suspect that it has something to do with the rate of download? What parameters are you giving the MetaUtil function?—

**Comment by kamicut** [comment]
Right, sorry about that. I got the error too, it means that the stream is shutting down [L62](https://github.com/osmlab/osm-meta-util/blob/master/index.js#L62) and we're still trying to push data to it [L57](https://github.com/osmlab/osm-meta-util/blob/master/index.js#L57)

**Comment by mikelmaron** [comment]
@kamicut I don't understand the issue ... why would the stream shut down too early?

**Comment by mikelmaron** [comment]
Should the stream ever be shut down in liveMode?

**Comment by mikelmaron** [comment]
Commenting out https://github.com/osmlab/osm-meta-util/blob/master/index.js#L62 keeps it running indefinitely. I think there is some logic that doesn't apply when it comes to liveMode,

**Comment by kamicut** [comment]
@mikelmaron I think you're right. I think I introduced a logic bug when creating the feature for scraping between two endpoints

**Comment by mikelmaron** [comment]
:+1:
